const pptxgen=require("pptxgenjs");
const C={white:"FFFFFF",offWhite:"FAFBFC",lightGray:"F3F4F6",navy:"1B2A4A",navyLight:"2D4A7A",accent:"2563EB",accentLight:"DBEAFE",accentMid:"93C5FD",textDark:"111827",textBody:"374151",textLight:"6B7280",textMuted:"9CA3AF",green:"059669",greenBg:"D1FAE5",amber:"D97706",amberBg:"FEF3C7",red:"DC2626",redBg:"FEE2E2",border:"E5E7EB"};
const F={sans:"Calibri",size:{hero:40,h1:24,h2:20,h3:16,body:14,label:12,caption:10}};
const L={W:10,H:5.625,mx:0.75,my:0.5,gap:0.3};
let pres;const T=12;
function addTopBar(slide){slide.addShape(pres.shapes.RECTANGLE,{x:0,y:0,w:L.W,h:0.035,fill:{color:C.accent}});}
function addFooter(slide,num){slide.addShape(pres.shapes.LINE,{x:L.mx,y:L.H-0.4,w:L.W-L.mx*2,h:0,line:{color:C.border,width:0.5}});slide.addText(`${num} / ${T}`,{x:L.W-1.5,y:L.H-0.38,w:1.2,h:0.3,fontSize:F.size.caption,fontFace:F.sans,color:C.textMuted,align:"right",shrinkText:true});slide.addText("P-05",{x:L.mx,y:L.H-0.38,w:2,h:0.3,fontSize:F.size.caption,fontFace:F.sans,color:C.textMuted,align:"left",shrinkText:true});}
function addTitle(slide,title,tag){if(tag){const tagW=tag.length*0.12+0.4;slide.addShape(pres.shapes.RECTANGLE,{x:L.mx,y:0.15,w:tagW,h:0.28,fill:{color:C.accentLight},rectRadius:0.05});slide.addText(tag,{x:L.mx,y:0.15,w:tagW,h:0.28,fontSize:F.size.caption,fontFace:F.sans,bold:true,color:C.accent,align:"center",valign:"middle",shrinkText:true});}slide.addText(title,{x:L.mx,y:tag?0.5:0.15,w:8.5,h:0.45,fontSize:F.size.h1,fontFace:F.sans,bold:true,color:C.textDark,shrinkText:true});}
function addCards(slide,cards,y,cardW,cardH){const cardGap=0.3,totalW=cardW*cards.length+cardGap*(cards.length-1),startX=(L.W-totalW)/2;cards.forEach((c,i)=>{const x=startX+i*(cardW+cardGap);slide.addShape(pres.shapes.RECTANGLE,{x,y,w:cardW,h:cardH,fill:{color:c.bg||C.offWhite},line:{color:c.borderColor||C.border,width:c.borderColor?1:0.5},rectRadius:0.05});slide.addText(c.label,{x,y:y+0.25,w:cardW,h:0.35,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:c.color||C.textDark,align:"center",shrinkText:true});slide.addText(c.desc,{x:x+0.15,y:y+0.65,w:cardW-0.3,h:cardH-0.85,fontSize:F.size.body,fontFace:F.sans,color:C.textBody,align:"center",lineSpacingMultiple:1.3,shrinkText:true});});}
function addInsight(slide,text,y){slide.addShape(pres.shapes.RECTANGLE,{x:L.mx,y,w:L.W-L.mx*2,h:0.4,fill:{color:C.accentLight},rectRadius:0.04});slide.addText(text,{x:L.mx+0.15,y,w:L.W-L.mx*2-0.3,h:0.4,fontSize:F.size.label,fontFace:F.sans,italic:true,color:C.textLight,valign:"middle",shrinkText:true});}
async function main(){pres=new pptxgen();pres.layout="LAYOUT_16x9";pres.author="Gorilla Knowledge";pres.title="P-05: 実装事例・未来へ";

{const s=pres.addSlide();s.background={color:C.navy};s.addText("実装事例・未来へ",{x:0.5,y:1.5,w:9,h:0.8,fontSize:F.size.hero,fontFace:F.sans,bold:true,color:C.white,align:"center",shrinkText:true});s.addShape(pres.shapes.LINE,{x:3.5,y:2.45,w:3,h:0,line:{color:C.accentMid,width:1.5}});s.addText("導入後の変化を見る",{x:0.5,y:2.65,w:9,h:0.45,fontSize:F.size.h2,fontFace:F.sans,color:C.accentMid,align:"center",shrinkText:true});s.addText("P-05  |  全社員向け  |  12分",{x:0.5,y:3.8,w:9,h:0.35,fontSize:F.size.label,fontFace:F.sans,color:C.textMuted,align:"center",shrinkText:true});}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"今日のゴール");addFooter(s,2);const goals=["企業導入後の時間軸での変化を理解する","実装事例から学べることを抽出する","これからの働き方の可能性を想像する"];goals.forEach((g,i)=>{const y=1.0+i*1.15;s.addText(String(i+1),{x:L.mx,y:y+0.05,w:0.5,h:0.5,fontSize:F.size.h2,fontFace:F.sans,bold:true,color:C.white,align:"center",valign:"middle",fill:{color:C.accent},shape:pres.shapes.OVAL,shrinkText:true});s.addText(g,{x:L.mx+0.7,y,w:7.5,h:0.6,fontSize:F.size.h3,fontFace:F.sans,color:C.textDark,valign:"middle",shrinkText:true});if(i<2)s.addShape(pres.shapes.LINE,{x:L.mx,y:y+0.8,w:L.W-L.mx*2,h:0,line:{color:C.border,width:0.5}});});}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"3つの実企業事例","CASE STUDIES");addFooter(s,3);addCards(s,[{label:"J:COM",desc:"通信・放送\n月1,500時間削減",color:C.accent,bg:C.accentLight,borderColor:C.accent},{label:"note",desc:"クリエイタープラットフォーム\n月3～4時間削減",color:C.green,bg:C.greenBg,borderColor:C.green},{label:"日本特殊陶業",desc:"製造業\n週3.1時間削減",color:C.amber,bg:C.amberBg,borderColor:C.amber}],1.0,2.5,2.0);addInsight(s,"業種・規模を問わず、導入3～6ヶ月で全社展開に至る",3.5);}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"導入後の成長ストーリー","TIMELINE");addFooter(s,4);const timeline=[{period:"導入3ヶ月目",change:"メール対応 2h → 1h（50%削減）",benefit:"浮いた1時間を顧客面談準備に充当"},{period:"導入6ヶ月目",change:"提案書作成 3日 → 1日（70%削減）",benefit:"提案件数2倍、成約率15%向上"},{period:"導入1年目",change:"事務作業 → 営業活動へ時間転用",benefit:"売上25%増加、従業員満足度向上"}];timeline.forEach((item,i)=>{const y=0.95+i*1.4;s.addShape(pres.shapes.RECTANGLE,{x:L.mx,y,w:L.W-L.mx*2,h:1.2,fill:{color:C.accentLight},rectRadius:0.05});s.addText(item.period,{x:L.mx+0.3,y:y+0.08,w:2,h:0.3,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:C.accent,shrinkText:true});s.addText(item.change,{x:L.mx+0.3,y:y+0.4,w:8.4,h:0.3,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:C.textDark,shrinkText:true});s.addText(item.benefit,{x:L.mx+0.3,y:y+0.72,w:8.4,h:0.35,fontSize:F.size.body,fontFace:F.sans,color:C.textBody,shrinkText:true});});}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"実演: 営業チームの1年成長記","DEMO TIMELINE");addFooter(s,5);s.addShape(pres.shapes.RECTANGLE,{x:L.mx,y:0.95,w:L.W-L.mx*2,h:1.8,fill:{color:C.lightGray},rectRadius:0.05});s.addText("【実演動画: 92.3秒】\n\n0-25秒: 導入3ヶ月。メール対応の時間短縮を実感\n25-45秒: 導入6ヶ月。提案書作成の効率化で提案件数が増加\n45-70秒: 導入1年。営業チーム全体の生産性が大きく向上\n70-92秒: これからのステップ。どう広げていくか",{x:L.mx+0.3,y:1.0,w:8.4,h:1.7,fontSize:F.size.body,fontFace:F.sans,color:C.textBody,lineSpacingMultiple:1.3,shrinkText:true});}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"これからの3ステップ","FIRST 3 STEPS");addFooter(s,6);addCards(s,[{label:"Step 1",desc:"Gmail での自動ドラフト機能から\n毎日使うメールで小さく成功",color:C.accent,bg:C.accentLight,borderColor:C.accent},{label:"Step 2",desc:"ドキュメントで提案書テンプレート\n作成時間が大幅短縮",color:C.green,bg:C.greenBg,borderColor:C.green},{label:"Step 3",desc:"スプレッドシートで営業データ分析\n経理データ整理も AI にお任せ",color:C.amber,bg:C.amberBg,borderColor:C.amber}],0.95,2.5,2.0);addInsight(s,"この3ステップなら、誰でも今週中に始められる",3.5);}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"未来の働き方","FUTURE OF WORK");addFooter(s,7);s.addShape(pres.shapes.RECTANGLE,{x:L.mx,y:0.95,w:L.W-L.mx*2,h:0.8,fill:{color:C.accentLight},rectRadius:0.05});s.addText("定型業務から『創造的仕事』へシフト。AI と人間の協働が当たり前になる",{x:L.mx+0.25,y:1.0,w:8.5,h:0.7,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:C.accent,valign:"middle",shrinkText:true});addCards(s,[{label:"事務作業",desc:"AI が自動化\n人間は監督役",color:C.lightGray,bg:C.lightGray},{label:"→",desc:"→",color:C.accent},{label:"創造的仕事",desc:"営業面談・戦略立案\n顧客との関係構築",color:C.accent,bg:C.accentLight,borderColor:C.accent}],2.1,2.2,1.4);}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"採用・継続に必要なこと","SUCCESS FACTORS");addFooter(s,8);const factors=[{label:"✓ 小さく始める",desc:"全社導入ではなく、10～20名規模のパイロット"},{label:"✓ 成功事例を共有",desc:"早期に『メール作成が半減した』事例をチーム内で共有"},{label:"✓ フィードバック循環",desc:"うまくいった使い方・失敗事例を組織で学ぶ"},{label:"✓ ルール・ガイドラインの明確化",desc:"何が OK で、何が NG か。投入してよいデータを定義"}];factors.forEach((f,i)=>{const y=0.95+i*0.95;s.addText(f.label,{x:L.mx+0.3,y,w:2.5,h:0.3,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:C.green,shrinkText:true});s.addText(f.desc,{x:L.mx+3.0,y,w:6,h:0.35,fontSize:F.size.body,fontFace:F.sans,color:C.textBody,shrinkText:true});});}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"年間200時間削減の価値","ROI CALCULATION");addFooter(s,9);s.addShape(pres.shapes.RECTANGLE,{x:L.mx,y:0.95,w:L.W-L.mx*2,h:2.8,fill:{color:C.greenBg},line:{color:C.green,width:1},rectRadius:0.05});s.addText("従業員1名あたり：年間200時間",{x:L.mx+0.3,y:1.05,w:8.4,h:0.3,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:C.green,shrinkText:true});s.addText("= 月16時間 = 日当たり30分\n\n100名いる企業なら：年間20,000時間削減\n= 1人分の雇用（年俸550万とすると）を生み出すのと同じ価値\n\n+ 成約率15%向上、顧客満足度向上\n→ ROI は計り知れない",{x:L.mx+0.3,y:1.4,w:8.4,h:1.3,fontSize:F.size.body,fontFace:F.sans,color:C.textBody,lineSpacingMultiple:1.4,shrinkText:true});}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"質問・相談","NEXT STEPS");addFooter(s,10);s.addShape(pres.shapes.RECTANGLE,{x:L.mx,y:1.0,w:L.W-L.mx*2,h:2.8,fill:{color:C.offWhite},line:{color:C.border,width:0.5},rectRadius:0.05});s.addText("P-01 から P-05 の5部構成で、Gemini Enterprise の全体像を学びました。",{x:L.mx+0.3,y:1.1,w:8.4,h:0.4,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:C.textDark,shrinkText:true});s.addText("ご不明な点やご質問があればお気軽にお聞きください。\n\nさらに詳しい実装や、社内での推進方法については、別途お話しします。",{x:L.mx+0.3,y:1.55,w:8.4,h:1.2,fontSize:F.size.body,fontFace:F.sans,color:C.textBody,lineSpacingMultiple:1.4,shrinkText:true});}

{const s=pres.addSlide();s.background={color:C.navy};s.addText("まとめ",{x:0.5,y:0.5,w:9,h:0.6,fontSize:F.size.h1,fontFace:F.sans,bold:true,color:C.white,align:"center",shrinkText:true});const summaries=["Gemini Enterprise は、導入後3～6ヶ月で組織全体の効率が劇的に改善される","年200時間削減 = 組織に新しい価値を創造する時間が生まれる","小さく始めて、成功を積み重ねることが最短ルート"];summaries.forEach((text,i)=>{const y=1.5+i*1.0;s.addText(String(i+1),{x:2.5,y,w:0.5,h:0.5,fontSize:F.size.h2,fontFace:F.sans,bold:true,color:C.navy,align:"center",valign:"middle",fill:{color:C.accentMid},shape:pres.shapes.OVAL,shrinkText:true});s.addText(text,{x:3.2,y,w:5,h:0.5,fontSize:F.size.h3,fontFace:F.sans,color:C.white,valign:"middle",shrinkText:true});});addFooter(s,11);}

{const s=pres.addSlide();s.background={color:C.navy};s.addText("P-05 修了",{x:0.5,y:1.8,w:9,h:0.7,fontSize:F.size.hero,fontFace:F.sans,bold:true,color:C.white,align:"center",shrinkText:true});s.addShape(pres.shapes.LINE,{x:3.5,y:2.65,w:3,h:0,line:{color:C.accentMid,width:1.5}});s.addText("全5講座修了。これからの一歩を踏み出そう",{x:0.5,y:2.8,w:9,h:0.45,fontSize:F.size.h2,fontFace:F.sans,color:C.accentMid,align:"center",shrinkText:true});s.addText("ありがとうございました",{x:0.5,y:3.8,w:9,h:0.35,fontSize:F.size.label,fontFace:F.sans,color:C.textMuted,align:"center",shrinkText:true});}

const outPath=__dirname+"/スライド.pptx";await pres.writeFile({fileName:outPath});console.log("Created: "+outPath);}
main().catch(err=>{console.error(err);process.exit(1);});
