const pptxgen = require("pptxgenjs");
const C = {white:"FFFFFF",offWhite:"FAFBFC",lightGray:"F3F4F6",navy:"1B2A4A",navyLight:"2D4A7A",accent:"2563EB",accentLight:"DBEAFE",accentMid:"93C5FD",textDark:"111827",textBody:"374151",textLight:"6B7280",textMuted:"9CA3AF",green:"059669",greenBg:"D1FAE5",amber:"D97706",amberBg:"FEF3C7",red:"DC2626",redBg:"FEE2E2",border:"E5E7EB"};
const F={sans:"Calibri",size:{hero:40,h1:24,h2:20,h3:16,body:14,label:12,caption:10}};
const L={W:10,H:5.625,mx:0.75,my:0.5,gap:0.3};
let pres;const T=12;
function addTopBar(slide){slide.addShape(pres.shapes.RECTANGLE,{x:0,y:0,w:L.W,h:0.035,fill:{color:C.accent}});}
function addFooter(slide,num){slide.addShape(pres.shapes.LINE,{x:L.mx,y:L.H-0.4,w:L.W-L.mx*2,h:0,line:{color:C.border,width:0.5}});slide.addText(`${num} / ${T}`,{x:L.W-1.5,y:L.H-0.38,w:1.2,h:0.3,fontSize:F.size.caption,fontFace:F.sans,color:C.textMuted,align:"right",shrinkText:true});slide.addText("P-04",{x:L.mx,y:L.H-0.38,w:2,h:0.3,fontSize:F.size.caption,fontFace:F.sans,color:C.textMuted,align:"left",shrinkText:true});}
function addTitle(slide,title,tag){if(tag){const tagW=tag.length*0.12+0.4;slide.addShape(pres.shapes.RECTANGLE,{x:L.mx,y:0.15,w:tagW,h:0.28,fill:{color:C.accentLight},rectRadius:0.05});slide.addText(tag,{x:L.mx,y:0.15,w:tagW,h:0.28,fontSize:F.size.caption,fontFace:F.sans,bold:true,color:C.accent,align:"center",valign:"middle",shrinkText:true});}slide.addText(title,{x:L.mx,y:tag?0.5:0.15,w:8.5,h:0.45,fontSize:F.size.h1,fontFace:F.sans,bold:true,color:C.textDark,shrinkText:true});}
function addCards(slide,cards,y,cardW,cardH){const cardGap=0.3,totalW=cardW*cards.length+cardGap*(cards.length-1),startX=(L.W-totalW)/2;cards.forEach((c,i)=>{const x=startX+i*(cardW+cardGap);slide.addShape(pres.shapes.RECTANGLE,{x,y,w:cardW,h:cardH,fill:{color:c.bg||C.offWhite},line:{color:c.borderColor||C.border,width:c.borderColor?1:0.5},rectRadius:0.05});slide.addText(c.label,{x,y:y+0.25,w:cardW,h:0.35,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:c.color||C.textDark,align:"center",shrinkText:true});slide.addText(c.desc,{x:x+0.15,y:y+0.65,w:cardW-0.3,h:cardH-0.85,fontSize:F.size.body,fontFace:F.sans,color:C.textBody,align:"center",lineSpacingMultiple:1.3,shrinkText:true});});}
function addInsight(slide,text,y){slide.addShape(pres.shapes.RECTANGLE,{x:L.mx,y,w:L.W-L.mx*2,h:0.4,fill:{color:C.accentLight},rectRadius:0.04});slide.addText(text,{x:L.mx+0.15,y,w:L.W-L.mx*2-0.3,h:0.4,fontSize:F.size.label,fontFace:F.sans,italic:true,color:C.textLight,valign:"middle",shrinkText:true});}
async function main(){pres=new pptxgen();pres.layout="LAYOUT_16x9";pres.author="Gorilla Knowledge";pres.title="P-04: セキュリティ・対象者ガイド";

{const s=pres.addSlide();s.background={color:C.navy};s.addText("セキュリティ・対象者ガイド",{x:0.5,y:1.5,w:9,h:0.8,fontSize:F.size.hero,fontFace:F.sans,bold:true,color:C.white,align:"center",shrinkText:true});s.addShape(pres.shapes.LINE,{x:3.5,y:2.45,w:3,h:0,line:{color:C.accentMid,width:1.5}});s.addText("信頼と安心の企業導入",{x:0.5,y:2.65,w:9,h:0.45,fontSize:F.size.h2,fontFace:F.sans,color:C.accentMid,align:"center",shrinkText:true});s.addText("P-04  |  全社員向け  |  12分",{x:0.5,y:3.8,w:9,h:0.35,fontSize:F.size.label,fontFace:F.sans,color:C.textMuted,align:"center",shrinkText:true});}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"今日のゴール");addFooter(s,2);const goals=["企業向けAIのセキュリティ要件を理解する","Gemini Enterprise がどの部門向けかを把握する","導入時の不安を解消する"];goals.forEach((g,i)=>{const y=1.0+i*1.15;s.addText(String(i+1),{x:L.mx,y:y+0.05,w:0.5,h:0.5,fontSize:F.size.h2,fontFace:F.sans,bold:true,color:C.white,align:"center",valign:"middle",fill:{color:C.accent},shape:pres.shapes.OVAL,shrinkText:true});s.addText(g,{x:L.mx+0.7,y,w:7.5,h:0.6,fontSize:F.size.h3,fontFace:F.sans,color:C.textDark,valign:"middle",shrinkText:true});if(i<2)s.addShape(pres.shapes.LINE,{x:L.mx,y:y+0.8,w:L.W-L.mx*2,h:0,line:{color:C.border,width:0.5}});});}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"企業データの懸念","CONCERNS");addFooter(s,3);s.addShape(pres.shapes.RECTANGLE,{x:L.mx,y:0.95,w:L.W-L.mx*2,h:0.7,fill:{color:C.redBg},line:{color:C.red,width:1},rectRadius:0.05});s.addText("『AI に企業データを預けて本当に安全？』という質問が必ず出ます。",{x:L.mx+0.25,y:1.0,w:8.5,h:0.6,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:C.red,valign:"middle",shrinkText:true});addCards(s,[{label:"情報漏洩",desc:"顧客情報が\n外部に漏れないか",color:C.red,bg:C.redBg,borderColor:C.red},{label:"権限管理",desc:"誰がどのデータを\n見られるのか",color:C.red,bg:C.redBg,borderColor:C.red},{label:"規制対応",desc:"HIPAA・PCI DSS\n対応しているか",color:C.red,bg:C.redBg,borderColor:C.red}],1.9,2.5,1.6);}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"Gemini Enterprise のセキュリティ","SECURITY FEATURES");addFooter(s,4);const features=[{label:"HIPAA / FedRAMP / ISO 27001",desc:"医療・政府機関レベルのセキュリティ認定済み"},{label:"CMEK・EKM対応",desc:"顧客が暗号化キーを自社で管理可能"},{label:"DLP（データ損失防止）",desc:"機密情報の流出を AI が自動検知・遮断"},{label:"VPC Service Controls",desc:"企業ネットワーク内での安全な実行"}];features.forEach((f,i)=>{const y=0.95+i*0.95;s.addShape(pres.shapes.RECTANGLE,{x:L.mx,y,w:L.W-L.mx*2,h:0.8,fill:{color:C.greenBg},line:{color:C.green,width:1},rectRadius:0.05});s.addText(f.label,{x:L.mx+0.3,y:y+0.05,w:4,h:0.3,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:C.green,shrinkText:true});s.addText(f.desc,{x:L.mx+0.3,y:y+0.38,w:8.4,h:0.3,fontSize:F.size.body,fontFace:F.sans,color:C.textBody,shrinkText:true});});}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"対象部門・ユースケース","WHO & HOW");addFooter(s,5);addCards(s,[{label:"営業部門",desc:"提案書・顧客資料の作成\nメール対応効率化",color:C.accent,bg:C.accentLight,borderColor:C.accent},{label:"企画・企業企画",desc:"レポート作成・データ分析\n市場調査・競合分析",color:C.green,bg:C.greenBg,borderColor:C.green},{label:"カスタマーサポート",desc:"問い合わせ対応の自動化\nナレッジベース充実",color:C.amber,bg:C.amberBg,borderColor:C.amber}],1.0,2.5,2.2);addInsight(s,"全部門で使える。導入者数が多いほどROIが高まる",3.6);}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"よくある懸念と回答","FAQ");addFooter(s,6);const faqs=[{q:"個人情報が Gemini に学習されない？",a:"✓ 企業ネットワーク内で処理。外部学習なし"},{q:"データはどこに保存される？",a:"✓ 日本企業ならアジアリージョン。地域規制対応"},{q:"退職者のアカウント削除後、データは消える？",a:"✓ RBAC（アクセス管理）で権限を即座に削除"}];faqs.forEach((f,i)=>{const y=1.0+i*1.3;s.addText(f.q,{x:L.mx+0.3,y,w:8.4,h:0.35,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:C.textDark,shrinkText:true});s.addText(f.a,{x:L.mx+0.3,y:y+0.4,w:8.4,h:0.35,fontSize:F.size.body,fontFace:F.sans,color:C.green,shrinkText:true});});}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"導入時の不安を払拭","CONFIDENCE");addFooter(s,7);s.addShape(pres.shapes.RECTANGLE,{x:L.mx,y:0.95,w:L.W-L.mx*2,h:1.2,fill:{color:C.accentLight},rectRadius:0.05});s.addText("実績例を見る",{x:L.mx+0.3,y:1.0,w:3,h:0.3,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:C.accent,shrinkText:true});s.addText("J:COM（通信大手）・note（スタートアップ）・日本特殊陶業（製造業）など、業種・規模を問わず導入成功。『うちだけが失敗する』ことはない。",{x:L.mx+0.3,y:1.35,w:8.4,h:0.7,fontSize:F.size.body,fontFace:F.sans,color:C.textBody,lineSpacingMultiple:1.3,shrinkText:true});addCards(s,[{label:"初期テスト",desc:"10～50名規模で\nパイロット導入",color:C.accent,bg:C.accentLight,borderColor:C.accent},{label:"部分展開",desc:"成功事例で説得\n段階的に部門展開",color:C.green,bg:C.greenBg,borderColor:C.green},{label:"全社導入",desc:"3～6ヶ月で\n成熟した運用へ",color:C.amber,bg:C.amberBg,borderColor:C.amber}],1.9,2.5,1.6);}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"導入前・導入後の比較","BEFORE & AFTER");addFooter(s,8);const headers=["","導入前","導入後"];const rows=[["セキュリティ","手動チェック→人為的ミス","AI が自動検知→0件漏洩"],["業務効率","メール・資料作成に時間","AI が支援→時間3割減"],["従業員満足","定型業務で疲弊","創造的仕事にシフト"]];const colW=[2,3.5,3.5];const startX=(L.W-colW.reduce((a,b)=>a+b,0))/2;const rowH=0.5;const startY=1.0;let cx=startX;headers.forEach((h,i)=>{s.addShape(pres.shapes.RECTANGLE,{x:cx,y:startY,w:colW[i],h:rowH,fill:{color:C.lightGray},line:{color:C.border,width:0.5}});s.addText(h,{x:cx,y:startY,w:colW[i],h:rowH,fontSize:F.size.body,fontFace:F.sans,bold:true,color:i===2?C.green:C.textDark,align:"center",valign:"middle",shrinkText:true});cx+=colW[i];});rows.forEach((row,ri)=>{cx=startX;const y=startY+rowH+ri*rowH;row.forEach((cell,ci)=>{s.addShape(pres.shapes.RECTANGLE,{x:cx,y,w:colW[ci],h:rowH,fill:{color:C.white},line:{color:C.border,width:0.5}});s.addText(cell,{x:cx+0.1,y,w:colW[ci]-0.2,h:rowH,fontSize:F.size.body,fontFace:F.sans,bold:ci===0,color:ci===0?C.textDark:C.textBody,align:ci===0?"left":"center",valign:"middle",shrinkText:true});cx+=colW[ci];});});}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"導入のための3ステップ","3STEPS");addFooter(s,9);const steps=[{step:"1",title:"経営層の理解",desc:"セキュリティ・ROI を説明。年200時間削減の価値を伝える"},{step:"2",title:"パイロット導入",desc:"1部門・10～50名で試す。成功事例を作る"},{step:"3",title:"段階展開",desc:"成功事例を横展開。各部門で最適化を進める"}];steps.forEach((step,i)=>{const y=1.0+i*1.2;s.addText(step.step,{x:L.mx,y,w:0.6,h:0.5,fontSize:F.size.h1,fontFace:F.sans,bold:true,color:C.white,align:"center",valign:"middle",fill:{color:C.accent},shape:pres.shapes.OVAL,shrinkText:true});s.addText(step.title,{x:L.mx+0.8,y:y+0.05,w:2.5,h:0.3,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:C.textDark,shrinkText:true});s.addText(step.desc,{x:L.mx+0.8,y:y+0.35,w:2.5,h:0.35,fontSize:F.size.label,fontFace:F.sans,color:C.textBody,shrinkText:true});});}

{const s=pres.addSlide();s.background={color:C.white};addTopBar(s);addTitle(s,"Q&A よくある質問","Q&A");addFooter(s,10);const qa=[{q:"政府機関でも使える？",a:"✓ FedRAMP 対応で米国政府機関でも利用可"},{q:"顧客データが Gemini に見られる？",a:"✓ 見られない。データは企業ネットワーク内処理のみ"},{q:"契約解除後、データは消える？",a:"✓ 契約終了後、自動削除。ポリシーで定義可能"}];qa.forEach((item,i)=>{const y=1.1+i*1.15;s.addText(item.q,{x:L.mx+0.3,y,w:4,h:0.3,fontSize:F.size.h3,fontFace:F.sans,bold:true,color:C.textDark,shrinkText:true});s.addText(item.a,{x:L.mx+4.5,y,w:4.2,h:0.35,fontSize:F.size.body,fontFace:F.sans,color:C.green,shrinkText:true});});}

{const s=pres.addSlide();s.background={color:C.navy};s.addText("まとめ",{x:0.5,y:0.5,w:9,h:0.6,fontSize:F.size.h1,fontFace:F.sans,bold:true,color:C.white,align:"center",shrinkText:true});const summaries=["セキュリティは万全。HIPAA・FedRAMP・ISO 27001 対応済み","業種・部門を問わず導入可能。実績豊富","パイロットから段階導入が最短成功ルート"];summaries.forEach((text,i)=>{const y=1.5+i*1.0;s.addText(String(i+1),{x:2.5,y,w:0.5,h:0.5,fontSize:F.size.h2,fontFace:F.sans,bold:true,color:C.navy,align:"center",valign:"middle",fill:{color:C.accentMid},shape:pres.shapes.OVAL,shrinkText:true});s.addText(text,{x:3.2,y,w:5,h:0.5,fontSize:F.size.h3,fontFace:F.sans,color:C.white,valign:"middle",shrinkText:true});});addFooter(s,11);s.addText("P-04",{x:L.mx,y:L.H-0.38,w:2,h:0.3,fontSize:F.size.caption,fontFace:F.sans,color:C.textMuted,align:"left",shrinkText:true});}

{const s=pres.addSlide();s.background={color:C.navy};s.addText("P-04 修了",{x:0.5,y:1.8,w:9,h:0.7,fontSize:F.size.hero,fontFace:F.sans,bold:true,color:C.white,align:"center",shrinkText:true});s.addShape(pres.shapes.LINE,{x:3.5,y:2.65,w:3,h:0,line:{color:C.accentMid,width:1.5}});s.addText("セキュリティの懸念は、もう過去の話",{x:0.5,y:2.8,w:9,h:0.45,fontSize:F.size.h2,fontFace:F.sans,color:C.accentMid,align:"center",shrinkText:true});s.addText("NEXT → P-05 実装事例・未来へ",{x:0.5,y:3.8,w:9,h:0.35,fontSize:F.size.label,fontFace:F.sans,color:C.textMuted,align:"center",shrinkText:true});}

const outPath=__dirname+"/スライド.pptx";await pres.writeFile({fileName:outPath});console.log("Created: "+outPath);}
main().catch(err=>{console.error(err);process.exit(1);});
